trigger:
- master

pool:
  vmImage: ubuntu-18.04

container: ubuntu:rolling

- script: |
    sudo apt-get -y update
    sudo apt-get -y install python3.7
    sudo apt-get -y install cython3
  displayName: 'Install Dependencies'

- script: |
    python3.7 setup.py build --export
  displayName: 'Build Linux/MacOS'

- task: CopyFiles@2
  inputs:
    contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'JacquesLucke'
    repositoryName: 'JacquesLucke/animation_nodes'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tag: 'daily'
    releaseNotesSource: 'inline'
    assets: '$(Build.SourcesDirectory)/*.zip'
    assetUploadMode: 'replace'
    isPreRelease: true
    addChangeLog: false
  displayName: 'Update Release'
