trigger:
- master

pool:
  vmImage: ubuntu-18.04

steps:
- script: |
    docker run -v $PWD:/t ubuntu:rolling /bin/bash -c "cd /t; apt-get -y update; apt-get -y install python3.7 cython3 g++; python3.7 setup.py build --export"

- task: CopyFiles@2
  inputs:
    contents: '*.zip'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'JacquesLucke'
    repositoryName: 'JacquesLucke/animation_nodes'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tag: 'daily'
    releaseNotesSource: 'inline'
    assets: '$(Build.SourcesDirectory)/*.zip'
    assetUploadMode: 'replace'
    isPreRelease: true
    addChangeLog: false
  displayName: 'Update Release'
